### ISSUE TITLE
ResolvePackageNotFound issue with pplacer

### ISSUE THREAD

**Issue by bstamps** [WatsonLab/MAGpy#2]
Hello, 

Having some trouble in the install- running the below

`conda env create -f MAGpy/envs/MAGpy-3.5.yaml`

Produces the below error- 

```
Solving environment: failed

ResolvePackageNotFound: 
  - pplacer==1.1.alpha17=0
```

Is this a conda issue, or something up with the .yaml file?

**Comment by mw55309** [comment]
Hmmm, it works for me...

pplacer is in bioconda (https://anaconda.org/bioconda/pplacer) and bioconda is listed as a source in the yaml

Maybe remove the "==1.1.alpha17=0" in MAGpy-3.5.yaml and see if that works?

**Comment by mw55309** [comment]
It does seem that other have had problems with that conda recipe:

https://github.com/matsen/pplacer/issues/360

Does:

```
conda install -c bioconda pplacer
```

Work for you?

Otherwise, I recommend installing pplacer outside of conda, making sure it is in the $PATH of all users who will run the jobs and on all the cluster nodes, removing pplacer from the YAML and go from there...

**Comment by bstamps** [comment]
This appears to be a more general issue with MacOS and pplacer- a precompiled binary won't run on a fresh MacOS install, or one with gsl installed... and there isn't currently a MacOS pplacer recipe on Conda. for now I would say close this issue - I'm going to move my install to Ubuntu or CentOS to minimize issues.
