### ISSUE TITLE
Exiting because a job execution failed. Look above for error message

### ISSUE THREAD

**Issue by zhibaosuo** [WatsonLab/MAGpy#30]
Hi, I try to run the MAGpy using my own binning genomes, but the error occurs, and I cannot see the reason from the snakemake.log. Here is the log file, can you please help me to see the cause of the error? Thank you!
[2021-05-24T184256.022975.snakemake.log](https://github.com/WatsonLab/MAGpy/files/6532110/2021-05-24T184256.022975.snakemake.log)

**Comment by mw55309** [comment]
Two errors occurred

FIrtsly in PhyloPhlan, this is nor surprise as the phylophlan functionality is broken - I am sorry! See https://github.com/WatsonLab/MAGpy/issues/29#issuecomment-778589844 for how to fix that.

The second job was checkm_plus

It may be that this is simply because you need to run:

```sh
chmod 755 scripts/*
```

Can you try that and get back to me?

**Comment by mw55309** [comment]
Hey

There is a new release today that fixes a lot of sourmash and phylophlan bugs

Please test it!

Cheers
Mick

**Comment by zhibaosuo** [comment]
Thank you, I tried the way you taught me and it worked. I will try the new release.
